routes/web.php
<?php



Auth::routes();
Route::view('/admin','admin')->name('admin')->middleware('auth');;
Route::get('/', 'HomeController@index')->name('home');
Route::resource('pelicula','PeliculaController')->middleware('auth');;
Route::resource('banner','BannerController')->middleware('auth');;
Route::resource('user','UsersController');
Route::resource('horario','HorarioController');
Route::resource('cartelera','CarteleraController');
Route::get('/image/file/{filename}', 'ShowImage')->name('image');

Route::get('pdf/{option}','PdfController@generatePDF2');

Route::get('pdf','PdfController@generatePDF');
Route::post('pdf','PdfController@obtenerFecha')->name('fecha');
Route::get('pdf/{from}/{to}','PdfController@generateFecha');
Route::get('/reporte','ReporteController@index')->name('reporte');

app/Horario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Horario extends Model{
    protected $table = 'horarios';

    protected $fillable = [
        'fecha','hora','sala','precio','pelicula_id'
    ];

    public function pelicula(){
        return $this->belongsTo(Pelicula::class);
    }
}

app/Http/Controllers/HorarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Horario;
use App\Pelicula;
class HorarioController extends Controller{
   
    public function index(){
        $horarios = Horario::orderBy('id','asc')->paginate(10); 
        return view('horarios.home',['horarios'=>$horarios]);
    }

    
    public function create(){
       $peliculas = Pelicula::orderBy('id','asc')->get();      
        
        return view('horarios.formulario',['peliculas'=>$peliculas]);
    }

   
    public function store(Request $request){
        $validate  = $this->validate($request,[
            'fecha'=> 'required',
            'hora' => 'required',
            'sala'=> 'required',
            'precio'=> 'required',
        ]);
        $fecha = $request->input('fecha');
        $hora = $request->input('hora');
        $sala = $request->input('sala');
        $precio = $request->input('precio');
        $peliculaId = $request->input('pelicula');

        $horario = new Horario();
        $horario->fecha = $fecha;
        $horario->hora = $hora;
        $horario->sala = $sala;
        $horario->precio = $precio;
        $horario->pelicula_id = $peliculaId;
        //var_dump($horario->precio);
        $horario->save();
       
       // return redirect('horario/create');
    }

   
    public function show($id)
    {
        //
    }

   
    public function edit($id){
        $horario = Horario::findOrFail($id);
        $peliculas = Pelicula::orderBy('id','asc')->get();      
        
        return view('horarios.edit',['peliculas'=>$peliculas,'horario'=>$horario]);
    }


    public function update(Request $request, $id){
        $validate  = $this->validate($request,[
            'fecha'=> 'required',
            'hora' => 'required',
            'sala'=> 'required',
            'precio'=> 'required',
        ]);
        $horario = Horario::find($id);
        $horario->fecha = $request->input('fecha');
        $horario->hora = $request->input('hora');
        $horario->sala = $request->input('sala');
        $horario->precio = $request->input('precio');
        
        $horario->save();
       
       return redirect('horario');
    }


    public function destroy($id){
        $horario = Horario::find($id);
        $horario->delete();
        return redirect('horario');
    }
}

resources/views/horarios/edit.blade.php
@extends('layouts.admin')

@section('content')
  {{$errors}}

    <div class="container">
        <div class="row">
            
           
            <div class="col-md">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Horario</h4>
                  <p class="card-category">Complete los datos</p>
                </div>
                <div class="card-body">
                   <form method="POST" action="{{ route('horario.update',$horario->id) }}">
                     @csrf
                     @method('PUT')
                    
                      
                    
                 
                  <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Fecha</label>
                          <input type="date" name="fecha" class="form-control"  value="{{ $horario->fecha}}">
                        </div>
                      </div>
                     <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Hora</label>
                          <input type="time" name="hora" class="form-control" value="{{ $horario->hora}}">
                          @error('hora')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>

                  </div>
                   
                    <div class="row">
                      <div class="col-md-5">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Sala</label>
                            <select class="form-control" name="sala" id="exampleFormControlSelect1">
                              <option value="Sala A">Sala A</option>
                              <option value="Sala B">Sala B</option>  
                              <option value="Sala C">Sala C</option>
                              <option value="Sala D">Sala D</option>
                              <option value="Sala Premium A">Sala Premium A</option>
                              <option value="Sala Premium B">Sala Premium B</option>
                            </select>
                        </div>
                      </div>
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">precio</label>
                          <input type="number" name="precio" class="form-control"  value="{{ $horario->precio}}">
                          @error('precio')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary pull-right">Guardar</button>
                    <div class="clearfix"></div>
                  </form>
                </div>

            
        </div>
    </div>
    

     <script>
            $('#inputGroupFile02').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html(fileName);
            })
        </script>
@endsection

resources/views/horarios/formulario.blade.php
@extends('layouts.admin')

@section('content')
  {{$errors}}

    <div class="container">
        <div class="row">
            
           
            <div class="col-md">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Horario</h4>
                  <p class="card-category">Complete los datos</p>
                </div>
                <div class="card-body">
                  <form method="POST" action="{{ route('horario.store') }}">
                    @csrf
                    
                      
                    <div class="row">
                      <div class="col-md-5">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Pelicula</label>
                            <select class="form-control" name="pelicula" id="exampleFormControlSelect1">
                              @foreach($peliculas as $pelicula)
                                <option value="{{$pelicula->id}}">{{$pelicula->titulo}}</option>
                              @endforeach
                            </select>
                        </div>
                      </div>
                      
                  </div>
                   
                 
                  <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Fecha</label>
                          <input type="date" name="fecha" class="form-control"  value="{{ old('fecha')}}">
                        </div>
                      </div>
                     <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Hora</label>
                          <input type="time" name="hora" class="form-control" value="{{ old('hora')}}">
                          @error('hora')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>

                  </div>
                   
                    <div class="row">
                      <div class="col-md-5">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Sala</label>
                            <select class="form-control" name="sala" id="exampleFormControlSelect1">
                              <option value="Sala A">Sala A</option>
                              <option value="Sala B">Sala B</option>  
                              <option value="Sala C">Sala C</option>
                              <option value="Sala D">Sala D</option>
                              <option value="Sala Premium A">Sala Premium A</option>
                              <option value="Sala Premium B">Sala Premium B</option>
                            </select>
                        </div>
                      </div>
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">precio</label>
                          <input type="number" name="precio" class="form-control"  value="{{ old('precio')}}">
                          @error('precio')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary pull-right">Guardar</button>
                    <div class="clearfix"></div>
                  </form>
                </div>

            
        </div>
    </div>
    

     <script>
            $('#inputGroupFile02').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html(fileName);
            })
        </script>
@endsection

resources/views/horarios/home.blade.php
@extends('layouts.admin')

@section('content')

  

    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
           <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                  <div class="card-icon">
                    <a  style="color:white"  href="{{ url('/pelicula/create') }}">
                    <i class="material-icons">add</i>
                    </a>
                  </div>
                  <p class="card-category">Horarios</p>
                  <h3 class="card-title">Nuevo</h3>
                  
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons"></i> 
                  </div>
                </div>
              </div>
             </div>

            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Horarios</h4>
                  <p class="card-category"> Here is a subtitle for this table</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>ID</th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th>Sala</th>
                        <th>Precio</th>
                        <th>Pelicula</th>
                        <th>Opciones</th>
                      </thead>
                      <tbody>

                        @foreach($horarios as $horario)
                        <tr>
                          <td>{{$horario->id}}</td>
                          <td>{{$horario->fecha}}</td>
                          <td>{{$horario->hora}}</td>
                          <td>{{$horario->sala}}</td>  
                          <td>${{$horario->precio}}</td>  
                          <td>{{$horario->pelicula->titulo}}</td>  
                          <td class="td-actions text-left">
                             <form  method="get" action="{{ route('horario.edit',$horario->id) }}">
                                
                                <button type="submit" rel="tooltip" title="Edit Task" class="btn btn-primary btn-link btn-sm">
                                    <i class="material-icons">edit</i>
                                  </button>
                              </form>
                              <form  method="post" action="{{ route('horario.destroy',$horario->id) }}">
                                @csrf
                                @method('DELETE')
                              <button type="submit" rel="tooltip" title="Remove" class="btn btn-danger btn-link btn-sm">
                                <i class="material-icons">close</i>
                              </button>
                              </form>
                          </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <!-- Paginacion -->
            <div class="row ">
              <div class="col-md-5 offset-md-4">
                <div class="clearfix">
                {{$horarios->links()}}
              </div>
              </div>
            </div>
    
    </div>
    
@endsection