routes/web.php
<?php



Auth::routes();
Route::view('/admin','admin')->name('admin')->middleware('auth');;
Route::get('/', 'HomeController@index')->name('home');
Route::resource('pelicula','PeliculaController')->middleware('auth');;
Route::resource('banner','BannerController')->middleware('auth');;
Route::resource('user','UsersController');
Route::resource('horario','HorarioController');
Route::resource('cartelera','CarteleraController');
Route::get('/image/file/{filename}', 'ShowImage')->name('image');

Route::get('pdf/{option}','PdfController@generatePDF2');

Route::get('pdf','PdfController@generatePDF');
Route::post('pdf','PdfController@obtenerFecha')->name('fecha');
Route::get('pdf/{from}/{to}','PdfController@generateFecha');
Route::get('/reporte','ReporteController@index')->name('reporte');

app/Pelicula.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pelicula extends Model{
     protected $table = 'peliculas';

    protected $fillable = [
        'titulo','duracion','clasificacion','genero','imagen','fechaEstreno','estatus','detalles_id'
    ];

    public function detalles(){
        return $this->belongsTo(Detalles::class);
    }
}

app/Http/Controllers/PeliculaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pelicula;
use App\Detalles;
class PeliculaController extends Controller
{
    
    public function index(){
        $peliculas = Pelicula::orderBy('id','asc')->paginate(1);      
        
        return view('pelicula.home',['peliculas'=>$peliculas]);
        
    }

    
    public function create(){
        return view('pelicula.formulario');
    }

   
    public function store(Request $request){
        // Validacion
        $validate  = $this->validate($request,[
            'titulo'=> 'required',
            'imagen' => 'required|image',
            'duracion'=> 'required|regex:^[0-9]+^',
            'clasificacion'=> 'required',
            'fechaEstreno'=> 'required',
        ]);
        ///Pelicula Aqui :v
        $image = $request->file('imagen');
        $titulo = $request->input('titulo');
        $duracion = $request->input('duracion');
        $clasificacion = $request->input('clasificacion');
        $genero = $request->input('genero');
        $estatus = $request->input('estatus');
        $fechaEstreno = $request->input('fechaEstreno');
        // Detalles
        $director = $request->input('director');   
        $actores = $request->input('actores'); 
        $sinopsis = $request->input('sinopsis');   
        $trailer = $request->input('trailer');
        // Save 
        $detalles = new Detalles();
        $detalles->director = $director;
        $detalles->actores = $actores;
        $detalles->sinopsis = $sinopsis;
        $detalles->trailer = $trailer;
        $detalles->save();
        ///
        $imageName = time().$image->getClientOriginalName();
        var_dump($imageName);
        var_dump($image);

        //Subir al servidor
        $pelicula = new Pelicula();
        $pelicula->titulo =$titulo;
        $pelicula->duracion = $duracion;
        $pelicula->clasificacion =$clasificacion;
        $pelicula->genero = $genero;
        $pelicula->estatus = $estatus;
        $pelicula->fechaEstreno =$fechaEstreno;
        $pelicula->detalles_id = $detalles->id;
       
        if ($image) {
           // Storage::disk('images')->put($imageName,File::get($image));
            $request->imagen->storeAs('public/images',$imageName);
            $pelicula->imagen = $imageName;
        }
        $pelicula->save();
        return redirect('pelicula');
    }

    
    public function show($id){
        //
    }

    
    public function edit($id){
        $pelicula = Pelicula::findOrFail($id);
        return view('pelicula.edit',['pelicula'=>$pelicula]);
    }

    
    public function update(Request $request, $id){
        $titulo = $request->input('titulo');
        $duracion = $request->input('duracion');
        $clasificacion = $request->input('clasificacion');
        $genero = $request->input('genero');
        $estatus = $request->input('estatus');
        $fechaEstreno = $request->input('fechaEstreno');
        // Detalles
        $director = $request->input('director');   
        $actores = $request->input('actores'); 
        $sinopsis = $request->input('sinopsis');   
        $trailer = $request->input('trailer');

        $detalles = Detalles::find($id);
        $detalles->director = $director;
        $detalles->actores = $actores;
        $detalles->sinopsis = $sinopsis;
        $detalles->trailer = $trailer;
        $detalles->save();

        $pelicula = Pelicula::find($id);
        $pelicula->titulo =$titulo;
        $pelicula->duracion = $duracion;
        $pelicula->clasificacion =$clasificacion;
        $pelicula->genero = $genero;
        $pelicula->estatus = $estatus;
        $pelicula->fechaEstreno =$fechaEstreno;
        $pelicula->detalles_id = $detalles->id;
        $pelicula->save();

        return redirect('pelicula');
    }

   
    public function destroy($id){
        $pelicula = Pelicula::find($id);
        if($pelicula->estatus == "Activo"){
            $pelicula->estatus = "Inactivo";
        }else{
            $pelicula->estatus = "Activo";
        }
        $pelicula->save();
         
        return redirect('pelicula');
    }
}

resources/views/pelicula/edit.blade.php
@extends('layouts.admin')

@section('content')
  {{$errors}}

    <div class="container">
        <div class="row">
            
           
            <div class="col-md">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Pelicula</h4>
                  <p class="card-category">Complete los datos</p>
                </div>
                <div class="card-body">
                  <div class="card-body">
                   <form method="POST" action="{{ route('pelicula.update',$pelicula->id) }}" enctype="multipart/form-data">
                     @csrf
                     @method('PUT')
                    <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Titulo</label>
                          <input type="text" name="titulo" class="form-control"  value="{{$pelicula->titulo}}">
                          @error('titulo')
                            <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                        
                        
                      </div>
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Duracion (Minutos)</label>
                          <input type="text" name="duracion" class="form-control"  value="{{$pelicula->duracion}}">
                          @error('duracion')
                            <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-5">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Clasificación</label>
                            <select class="form-control" name="clasificacion" id="exampleFormControlSelect1">
                              <option value="AA">AA</option>
                              <option value="A">A</option>  
                              <option value="B">B</option>
                              <option value="B15">B15</option>
                              <option value="C">C</option>
                              <option value="D">D</option>
                            </select>
                        </div>
                      </div>
                      <div class="col-md-5">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Genero</label>
                            <select class="form-control" name="genero" id="exampleFormControlSelect1">
                              <option value="Accion">Accion</option>
                              <option value="Aventura">Aventura </option>
                              <option value="Clasicas">Clasicas</option>
                              <option value="Comedia Romantica">Comedia Romantica</option>
                              <option value="Drama">Drama</option>
                              <option value="Terror">Terror</option>
                              <option value="Infantil">Infantil</option>
                              <option value="Accion y Aventura">Accion y Aventura</option>                  
                              <option value="Romantica">Romantica</option>                            
                            </select>
                        </div>
                      </div>
                  </div>
                   
                 
                  <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Fecha Estreno</label>
                          <input type="date" name="fechaEstreno" class="form-control"  value="{{ $pelicula->fechaEstreno}}">
                        </div>
                      </div>
                      <div class="col-md-5">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Estatus</label>
                            <select class="form-control" name="estatus" id="exampleFormControlSelect1">
                              <option value="Activo">Activo</option>
                              <option value="Inactivo">Inactivo</option>                              
                            </select>
                        </div>
                      </div>

                  </div>
                  <br>
                  <h4>Detalles pelicula</h4><br>
                   <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Director</label>
                          <input type="text" name="director" class="form-control" value="{{$pelicula->detalles->director}}">
                          @error('director')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Actores</label>
                          <input type="text" name="actores" class="form-control"  value="{{$pelicula->detalles->actores}}">
                          @error('actores')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Sinopsis</label>
                          <input type="text" name="sinopsis" class="form-control"  value="{{ $pelicula->detalles->sinopsis}}">
                          @error('sinopsis')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Trailer</label>
                          <input type="text" name="trailer" class="form-control"  value="{{ $pelicula->detalles->trailer}}">
                          @error('trailer')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary pull-right">Guardar</button>
                    <div class="clearfix"></div>
                  </form>
                </div>

            
        </div>
    </div>
    

     <script>
            $('#inputGroupFile02').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html(fileName);
            })
        </script>
@endsection

resources/views/pelicula/formulario.blade.php
@extends('layouts.admin')

@section('content')
  {{$errors}}

    <div class="container">
        <div class="row">
            
           
            <div class="col-md">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Pelicula</h4>
                  <p class="card-category">Complete los datos</p>
                </div>
                <div class="card-body">
                  <form method="POST" action="{{ route('pelicula.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Titulo</label>
                          <input type="text" name="titulo" class="form-control"  value="{{ old('titulo')}}">
                          @error('titulo')
                            <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                        
                        
                      </div>
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Duracion (Minutos)</label>
                          <input type="text" name="duracion" class="form-control"  value="{{ old('duracion')}}">
                          @error('duracion')
                            <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-5">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Clasificación</label>
                            <select class="form-control" name="clasificacion" id="exampleFormControlSelect1">
                              <option value="AA">AA</option>
                              <option value="A">A</option>  
                              <option value="B">B</option>
                              <option value="B15">B15</option>
                              <option value="C">C</option>
                              <option value="D">D</option>
                            </select>
                        </div>
                      </div>
                      <div class="col-md-5">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Genero</label>
                            <select class="form-control" name="genero" id="exampleFormControlSelect1">
                              <option value="Accion">Accion</option>
                              <option value="Aventura">Aventura </option>
                              <option value="Clasicas">Clasicas</option>
                              <option value="Comedia Romantica">Comedia Romantica</option>
                              <option value="Drama">Drama</option>
                              <option value="Terror">Terror</option>
                              <option value="Infantil">Infantil</option>
                              <option value="Accion y Aventura">Accion y Aventura</option>                  
                              <option value="Romantica">Romantica</option>                            
                            </select>
                        </div>
                      </div>
                  </div>
                    <div class="row">
                        <div class="col-md-7">
                            <div class="input-group">
                              <div class="custom-file border rounded">
                                <input type="file" name="imagen" class="custom-file-input bg-primary " id="inputGroupFile02">
                                <label class="custom-file-label " for="inputGroupFile02">Elija imagen</label>
                              </div>
                              @error('imagen')
                                  <span class="text-danger">{{ $message }}</span>
                              @enderror
                            </div>
                        </div>
                    </div>
                 
                  <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Fecha Estreno</label>
                          <input type="date" name="fechaEstreno" class="form-control"  value="{{ old('fechaEstreno')}}">
                        </div>
                      </div>
                      <div class="col-md-5">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Estatus</label>
                            <select class="form-control" name="estatus" id="exampleFormControlSelect1">
                              <option value="Activo">Activo</option>
                              <option value="Inactivo">Inactivo</option>                              
                            </select>
                        </div>
                      </div>

                  </div>
                  <br>
                  <h4>Detalles pelicula</h4><br>
                   <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Director</label>
                          <input type="text" name="director" class="form-control" value="{{ old('director')}}">
                          @error('director')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Actores</label>
                          <input type="text" name="actores" class="form-control"  value="{{ old('actores')}}">
                          @error('actores')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Sinopsis</label>
                          <input type="text" name="sinopsis" class="form-control"  value="{{ old('sinopsis')}}">
                          @error('sinopsis')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Trailer</label>
                          <input type="text" name="trailer" class="form-control"  value="{{ old('trailer')}}">
                          @error('trailer')
                              <span class="text-danger">{{ $message }}</span>
                          @enderror
                        </div>
                      </div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary pull-right">Guardar</button>
                    <div class="clearfix"></div>
                  </form>
                </div>

            
        </div>
    </div>
    

     <script>
            $('#inputGroupFile02').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html(fileName);
            })
        </script>
@endsection

resources/views/pelicula/home.blade.php
@extends('layouts.admin')

@section('content')

  

    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
           <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                  <div class="card-icon">
                    <a  style="color:white"  href="{{ url('/pelicula/create') }}">
                    <i class="material-icons">add</i>
                    </a>
                  </div>
                  <p class="card-category">Pelicula</p>
                  <h3 class="card-title">Nuevo</h3>
                  
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons"></i> 
                  </div>
                </div>
              </div>
             </div>

            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Pelicula</h4>
                  <p class="card-category"> Here is a subtitle for this table</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>ID</th>
                        <th>Titulo</th>
                        <th>Duración</th>
                        <th>Clasificación</th>
                        <th>Genero</th>
                        <th>Imagen</th>
                        <th>Estatus</th>
                        <th>Fecha Estreno</th>
                        <th>Opciones</th>
                      </thead>
                      <tbody>

                        @foreach($peliculas as $pelicula)
                        <tr>
                          <td>{{$pelicula->id}}</td>
                          <td>{{$pelicula->titulo}}</td>
                           <td>{{$pelicula->duracion}}</td>
                            <td>{{$pelicula->clasificacion}}</td>
                             <td>{{$pelicula->genero}}</td>
                          <td><img class="imagen" src="{{route('image',['filename'=>$pelicula->imagen])}}"></td>
                          <td>{{$pelicula->estatus}}</td>
                          <td>{{$pelicula->fechaEstreno}}</td>
                          <td class="td-actions text-left">
                             <form  method="get" action="{{ route('pelicula.edit',$pelicula->id) }}">
                                
                                <button type="submit" rel="tooltip" title="Edit Task" class="btn btn-primary btn-link btn-sm">
                                    <i class="material-icons">edit</i>
                                  </button>
                              </form>
                              <form  method="post" action="{{ route('pelicula.destroy',$pelicula->id) }}">
                                @csrf
                                @method('DELETE')
                              <button type="submit" rel="tooltip" title="Remove" class="btn btn-danger btn-link btn-sm">
                                <i class="material-icons">close</i>
                              </button>
                              </form>
                          </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <!-- Paginacion -->
            <div class="row ">
              <div class="col-md-5 offset-md-4">
                <div class="clearfix">
                {{$peliculas->links()}}
              </div>
              </div>
            </div>
    
    </div>
    
@endsection