routes/web.php
<?php



Auth::routes();
Route::view('/admin','admin')->name('admin')->middleware('auth');;
Route::get('/', 'HomeController@index')->name('home');
Route::resource('pelicula','PeliculaController')->middleware('auth');;
Route::resource('banner','BannerController')->middleware('auth');;
Route::resource('user','UsersController');
Route::resource('horario','HorarioController');
Route::resource('cartelera','CarteleraController');
Route::get('/image/file/{filename}', 'ShowImage')->name('image');

Route::get('pdf/{option}','PdfController@generatePDF2');

Route::get('pdf','PdfController@generatePDF');
Route::post('pdf','PdfController@obtenerFecha')->name('fecha');
Route::get('pdf/{from}/{to}','PdfController@generateFecha');
Route::get('/reporte','ReporteController@index')->name('reporte');

app/Banner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Banner extends Model{
    protected $table = 'banners';

    protected $fillable = [
        'titulo', 'archivo','estatus',
    ];
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use App\Banner;
use Illuminate\Pagination\LengthAwarePaginator;
class BannerController extends Controller{
    
    public function index(Request $request){
        $banners = Banner::orderBy('id','asc')->paginate(1);       
        return view('banner.home',['banners'=>$banners]);
    }

    
    public function create(){
        return view('banner.formulario');
    }

   
    public function store(Request $request){
       // Validacion
        $validate  = $this->validate($request,[
            'titulo'=> 'required',
            'imagen' => 'required|image'
        ]);


        $image = $request->file('imagen');
        $titulo = $request->input('titulo');
        $estatus = $request->input('estatus');
       
        $imageName = time().$image->getClientOriginalName();
        var_dump($imageName);
        var_dump($image);

        //Subir al servidor
        $banner = new Banner();
        $banner->titulo =$titulo;
        $banner->estatus = $estatus;

       
        if ($image) {
           // Storage::disk('images')->put($imageName,File::get($image));
            $request->imagen->storeAs('public/images',$imageName);
            $banner->archivo = $imageName;
        }
        $banner->save();
        return redirect('banner');
        
    }


    
    public function show($id){
        //
    }

    
    public function edit($id)
    {
        //
    }

 
    public function update(Request $request, $id){
        $banner = Banner::find($id);
        if($banner->estatus == "Activo"){
            $banner->estatus = "Inactivo";
        }else{
            $banner->estatus = "Activo";
        }
        $banner->save();
         
        return redirect('banner');
    }

    
    public function destroy($id)
    {
        //
    }
}

resources/views/banner/formulario.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            
           
            <div class="col-md">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Banner</h4>
                  <p class="card-category">Complete los datos</p>
                </div>
                <div class="card-body">
                  <form method="POST" action="{{ route('banner.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                      <div class="col-md-7">
                        <div class="form-group">
                          <label class="bmd-label-floating">Titulo</label>
                          <input type="text" name="titulo" class="form-control">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                        <div class="col-md-7">
                            <div class="input-group">
                              <div class="custom-file border rounded">
                                <input type="file" name="imagen" class="custom-file-input bg-primary " id="inputGroupFile02">
                                <label class="custom-file-label " for="inputGroupFile02">Elija imagen</label>
                              </div>
                      
                            </div>
                        </div>
                    </div>

                  <div class="row">
                      <div class="col-md-7">
                          <div class="form-group">
                            <label for="exampleFormControlSelect1">Estatus</label>
                            <select class="form-control" name="estatus" id="exampleFormControlSelect1">
                              <option value="Activo">Activo</option>
                              <option value="Inactivo">Inactivo</option>                              
                            </select>
                        </div>
                      </div>
                  </div>
                    
                    <button type="submit" class="btn btn-primary pull-right">Guardar</button>
                    <div class="clearfix"></div>
                  </form>
                </div>

            
        </div>
    </div>

     <script>
            $('#inputGroupFile02').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html(fileName);
            })
        </script>
@endsection

resources/views/banner/home.blade.php
@extends('layouts.admin')

@section('content')

  

    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
           <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                  <div class="card-icon">
                    <a  style="color:white"  href="{{ url('/banner/create') }}">
                    <i class="material-icons">add</i>
                    </a>
                  </div>
                  <p class="card-category">Banner</p>
                  <h3 class="card-title">Nuevo</h3>
                  
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons"></i> 
                  </div>
                </div>
              </div>
             </div>

            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Banner</h4>
                  <p class="card-category"> Here is a subtitle for this table</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>ID</th>
                        <th>Titulo</th>
                        <th>Imagen</th>
                        <th>Estatus</th>
                        <th>Opciones</th>
                      </thead>
                      <tbody>

                        @foreach($banners as $banner)
                        <tr>
                          <td>{{$banner->id}}</td>
                          <td>{{$banner->titulo}}</td>
                          <td><img class="imagen" src="{{route('image',['filename'=>$banner->archivo])}}"></td>
                          <td>{{$banner->estatus}}</td>
                          <td class="td-actions text-left">
                            <form  method="post" action="{{ route('banner.update',$banner->id) }}">
                              @csrf
                              @method("PUT") 
                              <button type="submit" rel="tooltip" title="Desactiva" class="btn btn-danger btn-link btn-sm">
                                @if($banner->estatus == 'Activo')
                                  <i class="material-icons">close</i>
                                @else
                                  <i class="material-icons">done</i>
                                @endif
                              </button>
                               </form>
                          </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <!-- Paginacion -->
            <div class="row ">
              <div class="col-md-5 offset-md-4">
                <div class="clearfix">
                {{$banners->links()}}
              </div>
              </div>
            </div>
    
    </div>
    <script>
    
    $(document).ready(function() {
        $('.active').click(function () {
            $.ajax({
            url : 'api/banner?page=1',
            dataType: 'html',
        }).done(function (data) {
          var json = $.parseJSON(data);
            $('tbody').html(recorrer(json.data));
            
            
        }).fail(function () {
            alert('data load failed.');
        });
        });
        $(document).on('click', '.pagination a', function (event) {
          
            getBlogs($(this).attr('href').split('page=')[1]);
            event.preventDefault();
        });
    });
    function getBlogs(page) {
        $.ajax({
            url : 'api/banner?page=' + page,
            dataType: 'html',
        }).done(function (data) {
          var json = $.parseJSON(data);
        
          $('tbody').html(recorrer(json.data));
            
            
        }).fail(function () {
            alert('data load failed.');
        });
    }
    function recorrer(data) {
      let salida;
      $.each(data,function(i, v) {
          salida += "<tr>";
          salida += "<td>"+v.id+"</td>";
          salida += "<td>"+v.titulo+"</td>";
          salida += "<td><img class='imagen' src='/image/file/"+v.archivo+"'></td>";
          salida += "<td>"+v.estatus+"</td>";
          salida +=  '<td class="td-actions text-left">';
          salida += "<form  method='post' action='banner/"+v.id+"'>";
          salida += '@csrf';
          salida += '@method("PUT")'; 
          salida += '<button type="submit" rel="tooltip" title="Remove" class="btn btn-danger btn-link btn-sm">';
          salida += ' <i class="material-icons">close</i>';
          salida += '</button>';
          salida += '</form>';
          salida += '</td>';
          
          // console.log( i , v);
      });
      return salida;
    }
    </script>
@endsection